return {
	nodes = {
		[" "] = {name = "air"},
		["."] = {name = "default:dirt"},
		["w"] = {name = "default:cobble"},
		["M"] = {name = "boulder_dig:magic_wall"},
		["X"] = {name = "boulder_dig:exit_dormant"},
		--["H"] = {name = "HIDDENOUTBOX"},
		["W"] = {name = "default:steelblock"},
		--["Q"] = {name = "FIREFLYl"},
		--["o"] = {name = "FIREFLYu"},
		--["O"] = {name = "FIREFLYr"},
		--["q"] = {name = "FIREFLYd"},
		["r"] = {name = "boulders:boulder"},
		--["rf"] = {name = "BOULDERf"},
		["d"] = {name = "boulder_dig:gemstone"},
		--["df"] = {name = "DIAMONDf"},
		--["P"] = {name = "INBOX"},
		--["x"] = {name = "HEXPANDINGWALL"},
		--["v"] = {name = "VEXPANDINGWALL"},
		--["V"] = {name = "EXPANDINGWALL"},	
		--[" "] = {name = "air"},
		--["c"] = {name = "BUTTERFLYd"},
		["C"] = {name = "boulder_dig:butterfly"},
		--["b"] = {name = "BUTTERFLYu"},
		--["B"] = {name = "BUTTERFLYr"},
		["a"] = {name = "boulder_dig:amoeba"},
		--["s"] = {name = "SLIME"},	
		["t"] = {name = "xpanes:bar_flat"},
	},
	layers = {
		{
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
		},

		{
			"tttttttttttttttttttttttttttttt",
			"t. . . . . . . . . . . . . . t",
			"t. . . . . . . . . . . . . . t",
			"tX . . . . . . . . . . . . . t",
			"t. . . . . . . . . . . . . . t",
			"t. . . . . . . . . . . . . . t",
			"tttttttttttttttttttttttttttttt",			
		},
		{
			"tttttttttttttttttttttttttttttt",
			"t                            t",
			"t                            t",
			"t                            t",
			"t                            t",
			"t                            t",
			"tttttttttttttttttttttttttttttt",		
		},
		{
			"tttttttttttttttttttttttttttttt",
			"tMMMMMMMMMMMMMMMMMMMMMMMMMMMMt",
			"tMMMMMMMMMMMMMMMMMMMMMMMMMMMMt",
			"tMMMMMMMMMMMMMMMMMMMMMMMMMM Mt",
			"tMMMMMMMMMMMMMMMMMMMMMMMMMMMMt",
			"tMMMMMMMMMMMMMMMMMMMMMMMMMMMMt",
			"tttttttttttttttttttttttttttttt",
		},

		{
			"tttttttttttttttttttttttttttttt",
			"t     r      r   r         r t",
			"t r         r      r    r    t",
			"t         r           r     rt",
			"t r          r               t",
			"t    r   r      r   r        t",
			"tttttttttttttttttttttttttttttt",	
		},
		{
			"tttttttttttttttttttttttttttttt",
			"t                            t",
			"t                            t",
			"t                            t",
			"t                            t",
			"t                            t",
			"tttttttttttttttttttttttttttttt",	
		},
		{
			"tttttttttttttttttttttttttttttt",
			"tttttttttttttttttttttttttttttt",
			"tttttttttttttttttttttttttttttt",
			"tttttttttttttttttttttttttttttt",
			"tttttttttttttttttttttttttttttt",
			"tttttttttttttttttttttttttttttt",
			"tttttttttttttttttttttttttttttt",
		},

	},
}