return {
	nodes = {
		[" "] = {name = "air"},
		["."] = {name = "default:dirt"},
		["w"] = {name = "default:cobble"},
		["M"] = {name = "boulder_dig:magic_wall"},
		["X"] = {name = "boulder_dig:exit_dormant"},
		--["H"] = {name = "HIDDENOUTBOX"},
		["W"] = {name = "default:steelblock"},
		["Q"] = {name = "boulder_dig:firefly"},  --left
		["o"] = {name = "boulder_dig:firefly_right"},  --up
		["O"] = {name = "boulder_dig:firefly_right"},  --right
		["q"] = {name = "boulder_dig:firefly_right"},   --down
		["r"] = {name = "boulders:boulder"},
		--["rf"] = {name = "BOULDERf"},
		["d"] = {name = "boulder_dig:gemstone"},
		--["df"] = {name = "DIAMONDf"},
		--["P"] = {name = "INBOX"},
		["x"] = {name = "boulder_dig:x_expanding_wall"},
		["v"] = {name = "boulder_dig:z_expanding_wall"},
		["V"] = {name = "boulder_dig:expanding_wall"},	
		["c"] = {name = "boulder_dig:butterfly_right"},  --down
		["C"] = {name = "boulder_dig:butterfly"},    --left
		["b"] = {name = "boulder_dig:butterfly_right"},  --up
		["B"] = {name = "boulder_dig:butterfly_right"},   --right
		["a"] = {name = "boulder_dig:amoeba"},
		["s"] = {name = "boulder_dig:slime"},	
		["t"] = {name = "xpanes:bar_flat"},
		["D"] = {name = "boulders:dropper"},
		["L"] = {name = "default:lava_source"},
	},
	layers = {
		{
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
		},

		{
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWLLWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWLLWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
		},
		{
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWW  WWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWW  WWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
			"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
		},
		{
			"tttttttttttttttttttttttttttttt",
			"tWWWWWWWWWWWWwwwwWWWWWWWWWWWWt",
			"tWWWWWWWWWWWWw  wWWWWWWWWWWWWt",
			"tWWWWWWWWWWWWw  wWWWWWWWWWWWWt",
			"tWWWWWWWWWWWWwwwwWWWWWWWWWWWWt",
			"tttttttttttttttttttttttttttttt",
		},
		{
			"tttttttttttttttttttttttttttttt",
			"t...........W    W....r...r..t",
			"t......r....W    W..r.......rt",
			"td..........W    W.......r...t",
			"t......r....W    W...r.......t",
			"tttttttttttttttttttttttttttttt",
		},		
		{
			"tttttttttttttttttttttttttttttt",
			"t..r........W    W.r.........t",
			"t.........r.W    W..r.....d.rt",
			"t...r.......W    W...d.......t",
			"t.r....r....W    W...r.....r.t",
			"tttttttttttttttttttttttttttttt",
		},				
		{
			"tttttttttttttttttttttttttttttt",
			"t..r........W    W.r.........t",
			"t.........r.. ww ...r.....d.rt",
			"t...r........ ww ....d.......t",
			"t.r....r....W    W...r.....r.t",
			"tttttttttttttttttttttttttttttt",
		},		
		{
			"tttttttttttttttttttttttttttttt",
			"t...........W    W....r...r..t",
			"t......r..... ww ...r.......rt",
			"td........... ww ........r...t",
			"t......r....W    W...r.......t",
			"tttttttttttttttttttttttttttttt",
		},	
		{
			"tttttttttttttttttttttttttttttt",
			"tWWWWWWWWWWWW    WWWWWWWWWWWWt",
			"tWWWWWWWWWWWW    WWWWWWWWWWWWt",
			"tWWWWWWWWWWWW    WWWWWWWWWWWWt",
			"tWWWWWWWWWWWW    WWWWWWWWWWWWt",
			"tttttttttttttttttttttttttttttt",
		},	
		{
			"tttttttttttttttttttttttttttttt",
			"tWWWWWWWWWWWWwwwwWWWWWWWWWWWWt",
			"tWWWWWWWWWWWWw  wWWWWWWWWWWWWt",
			"tWWWWWWWWWWWWw  wWWWWWWWWWWWWt",
			"tWWWWWWWWWWWWwwwwWWWWWWWWWWWWt",
			"tttttttttttttttttttttttttttttt",
		},	
		{
			"tttttttttttttttttttttttttttttt",
			"tWWWWWWWWWWWW    WWWWWWWWWWWWt",
			"tWWWWWWWWWWWW    WWWWWWWWWWWWt",
			"tWWWWWWWWWWWW    WWWWWWWWWWWWt",
			"tWWWWWWWWWWWW    WWWWWWWWWWWWt",
			"tttttttttttttttttttttttttttttt",
		},	
		{
			"tttttttttttttttttttttttttttttt",
			"tWWWWWWWWWWWW    WWWWWWWWWWWWt",
			"tWWWWWWWWWWWW    WWWWWWWWWWWWt",
			"tWWWWWWWWWWWW    WWWWWWWWWWWWt",
			"tWWWWWWWWWWWW    WWWWWWWWWWWWt",
			"tttttttttttttttttttttttttttttt",
		},			
		{
			"tttttttttttttttttttttttttttttt",
			"t                            t",
			"t                            t",
			"t                            t",
			"t                            t",
			"tttttttttttttttttttttttttttttt",	
		},
		{
			"tttttttttttttttttttttttttttttt",
			"tttttttttttttttttttttttttttttt",
			"tttttttttttttttttttttttttttttt",
			"tttttttttttttttttttttttttttttt",
			"tttttttttttttttttttttttttttttt",
			"tttttttttttttttttttttttttttttt",
		},

	},
}